# Generated by Django 3.0.5 on 2021-05-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('STime', models.TimeField()),
                ('ETime', models.TimeField()),
                ('QuestionCount', models.CharField(max_length=20)),
                ('Tmarks', models.CharField(max_length=20)),
                ('Duration', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('Wid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Noface', models.IntegerField()),
                ('Multiface', models.IntegerField()),
                ('Ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Exams')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('Qid', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.PositiveIntegerField(default=0)),
                ('Question', models.TextField(max_length=500)),
                ('option1', models.CharField(max_length=20)),
                ('option2', models.CharField(max_length=20)),
                ('option3', models.CharField(max_length=20)),
                ('option4', models.CharField(max_length=20)),
                ('Answer', models.CharField(max_length=1)),
                ('Ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Exams')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('Mid', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('marks', models.CharField(max_length=3)),
                ('Ename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Exams')),
            ],
        ),
    ]
